package com.ps.model.product;

import java.io.Serializable;

public class Food implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_food.fid
     *
     * @mbg.generated
     */
    private Integer fid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_food.fname
     *
     * @mbg.generated
     */
    private String fname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_food.price
     *
     * @mbg.generated
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_food.depict
     *
     * @mbg.generated
     */
    private String depict;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_food.cid
     *
     * @mbg.generated
     */
    private Integer cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_food.fimage
     *
     * @mbg.generated
     */
    private String fimage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tab_food
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_food.fid
     *
     * @return the value of tab_food.fid
     *
     * @mbg.generated
     */
    public Integer getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_food.fid
     *
     * @param fid the value for tab_food.fid
     *
     * @mbg.generated
     */
    public void setFid(Integer fid) {
        this.fid = fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_food.fname
     *
     * @return the value of tab_food.fname
     *
     * @mbg.generated
     */
    public String getFname() {
        return fname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_food.fname
     *
     * @param fname the value for tab_food.fname
     *
     * @mbg.generated
     */
    public void setFname(String fname) {
        this.fname = fname == null ? null : fname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_food.price
     *
     * @return the value of tab_food.price
     *
     * @mbg.generated
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_food.price
     *
     * @param price the value for tab_food.price
     *
     * @mbg.generated
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_food.depict
     *
     * @return the value of tab_food.depict
     *
     * @mbg.generated
     */
    public String getDepict() {
        return depict;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_food.depict
     *
     * @param depict the value for tab_food.depict
     *
     * @mbg.generated
     */
    public void setDepict(String depict) {
        this.depict = depict == null ? null : depict.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_food.cid
     *
     * @return the value of tab_food.cid
     *
     * @mbg.generated
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_food.cid
     *
     * @param cid the value for tab_food.cid
     *
     * @mbg.generated
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_food.fimage
     *
     * @return the value of tab_food.fimage
     *
     * @mbg.generated
     */
    public String getFimage() {
        return fimage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_food.fimage
     *
     * @param fimage the value for tab_food.fimage
     *
     * @mbg.generated
     */
    public void setFimage(String fimage) {
        this.fimage = fimage == null ? null : fimage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_food
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Food other = (Food) that;
        return (this.getFid() == null ? other.getFid() == null : this.getFid().equals(other.getFid()))
            && (this.getFname() == null ? other.getFname() == null : this.getFname().equals(other.getFname()))
            && (this.getPrice() == null ? other.getPrice() == null : this.getPrice().equals(other.getPrice()))
            && (this.getDepict() == null ? other.getDepict() == null : this.getDepict().equals(other.getDepict()))
            && (this.getCid() == null ? other.getCid() == null : this.getCid().equals(other.getCid()))
            && (this.getFimage() == null ? other.getFimage() == null : this.getFimage().equals(other.getFimage()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_food
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getFid() == null) ? 0 : getFid().hashCode());
        result = prime * result + ((getFname() == null) ? 0 : getFname().hashCode());
        result = prime * result + ((getPrice() == null) ? 0 : getPrice().hashCode());
        result = prime * result + ((getDepict() == null) ? 0 : getDepict().hashCode());
        result = prime * result + ((getCid() == null) ? 0 : getCid().hashCode());
        result = prime * result + ((getFimage() == null) ? 0 : getFimage().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_food
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", fid=").append(fid);
        sb.append(", fname=").append(fname);
        sb.append(", price=").append(price);
        sb.append(", depict=").append(depict);
        sb.append(", cid=").append(cid);
        sb.append(", fimage=").append(fimage);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}