package com.ps.model.product;

import java.io.Serializable;
import java.util.Date;

public class Product implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pid
     *
     * @mbg.generated
     */
    private String pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pname
     *
     * @mbg.generated
     */
    private String pname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.market_price
     *
     * @mbg.generated
     */
    private Double marketPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.shop_price
     *
     * @mbg.generated
     */
    private Double shopPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pimage
     *
     * @mbg.generated
     */
    private String pimage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pdate
     *
     * @mbg.generated
     */
    private Date pdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.is_hot
     *
     * @mbg.generated
     */
    private Integer isHot;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pdesc
     *
     * @mbg.generated
     */
    private String pdesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pflag
     *
     * @mbg.generated
     */
    private Integer pflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.cid
     *
     * @mbg.generated
     */
    private String cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pid
     *
     * @return the value of product.pid
     *
     * @mbg.generated
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pid
     *
     * @param pid the value for product.pid
     *
     * @mbg.generated
     */
    public void setPid(String pid) {
        this.pid = pid == null ? null : pid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pname
     *
     * @return the value of product.pname
     *
     * @mbg.generated
     */
    public String getPname() {
        return pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pname
     *
     * @param pname the value for product.pname
     *
     * @mbg.generated
     */
    public void setPname(String pname) {
        this.pname = pname == null ? null : pname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.market_price
     *
     * @return the value of product.market_price
     *
     * @mbg.generated
     */
    public Double getMarketPrice() {
        return marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.market_price
     *
     * @param marketPrice the value for product.market_price
     *
     * @mbg.generated
     */
    public void setMarketPrice(Double marketPrice) {
        this.marketPrice = marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.shop_price
     *
     * @return the value of product.shop_price
     *
     * @mbg.generated
     */
    public Double getShopPrice() {
        return shopPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.shop_price
     *
     * @param shopPrice the value for product.shop_price
     *
     * @mbg.generated
     */
    public void setShopPrice(Double shopPrice) {
        this.shopPrice = shopPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pimage
     *
     * @return the value of product.pimage
     *
     * @mbg.generated
     */
    public String getPimage() {
        return pimage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pimage
     *
     * @param pimage the value for product.pimage
     *
     * @mbg.generated
     */
    public void setPimage(String pimage) {
        this.pimage = pimage == null ? null : pimage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pdate
     *
     * @return the value of product.pdate
     *
     * @mbg.generated
     */
    public Date getPdate() {
        return pdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pdate
     *
     * @param pdate the value for product.pdate
     *
     * @mbg.generated
     */
    public void setPdate(Date pdate) {
        this.pdate = pdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.is_hot
     *
     * @return the value of product.is_hot
     *
     * @mbg.generated
     */
    public Integer getIsHot() {
        return isHot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.is_hot
     *
     * @param isHot the value for product.is_hot
     *
     * @mbg.generated
     */
    public void setIsHot(Integer isHot) {
        this.isHot = isHot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pdesc
     *
     * @return the value of product.pdesc
     *
     * @mbg.generated
     */
    public String getPdesc() {
        return pdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pdesc
     *
     * @param pdesc the value for product.pdesc
     *
     * @mbg.generated
     */
    public void setPdesc(String pdesc) {
        this.pdesc = pdesc == null ? null : pdesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pflag
     *
     * @return the value of product.pflag
     *
     * @mbg.generated
     */
    public Integer getPflag() {
        return pflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pflag
     *
     * @param pflag the value for product.pflag
     *
     * @mbg.generated
     */
    public void setPflag(Integer pflag) {
        this.pflag = pflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.cid
     *
     * @return the value of product.cid
     *
     * @mbg.generated
     */
    public String getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.cid
     *
     * @param cid the value for product.cid
     *
     * @mbg.generated
     */
    public void setCid(String cid) {
        this.cid = cid == null ? null : cid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Product other = (Product) that;
        return (this.getPid() == null ? other.getPid() == null : this.getPid().equals(other.getPid()))
            && (this.getPname() == null ? other.getPname() == null : this.getPname().equals(other.getPname()))
            && (this.getMarketPrice() == null ? other.getMarketPrice() == null : this.getMarketPrice().equals(other.getMarketPrice()))
            && (this.getShopPrice() == null ? other.getShopPrice() == null : this.getShopPrice().equals(other.getShopPrice()))
            && (this.getPimage() == null ? other.getPimage() == null : this.getPimage().equals(other.getPimage()))
            && (this.getPdate() == null ? other.getPdate() == null : this.getPdate().equals(other.getPdate()))
            && (this.getIsHot() == null ? other.getIsHot() == null : this.getIsHot().equals(other.getIsHot()))
            && (this.getPdesc() == null ? other.getPdesc() == null : this.getPdesc().equals(other.getPdesc()))
            && (this.getPflag() == null ? other.getPflag() == null : this.getPflag().equals(other.getPflag()))
            && (this.getCid() == null ? other.getCid() == null : this.getCid().equals(other.getCid()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getPid() == null) ? 0 : getPid().hashCode());
        result = prime * result + ((getPname() == null) ? 0 : getPname().hashCode());
        result = prime * result + ((getMarketPrice() == null) ? 0 : getMarketPrice().hashCode());
        result = prime * result + ((getShopPrice() == null) ? 0 : getShopPrice().hashCode());
        result = prime * result + ((getPimage() == null) ? 0 : getPimage().hashCode());
        result = prime * result + ((getPdate() == null) ? 0 : getPdate().hashCode());
        result = prime * result + ((getIsHot() == null) ? 0 : getIsHot().hashCode());
        result = prime * result + ((getPdesc() == null) ? 0 : getPdesc().hashCode());
        result = prime * result + ((getPflag() == null) ? 0 : getPflag().hashCode());
        result = prime * result + ((getCid() == null) ? 0 : getCid().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", pid=").append(pid);
        sb.append(", pname=").append(pname);
        sb.append(", marketPrice=").append(marketPrice);
        sb.append(", shopPrice=").append(shopPrice);
        sb.append(", pimage=").append(pimage);
        sb.append(", pdate=").append(pdate);
        sb.append(", isHot=").append(isHot);
        sb.append(", pdesc=").append(pdesc);
        sb.append(", pflag=").append(pflag);
        sb.append(", cid=").append(cid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}